// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7lAG4euhWTkFnQnd8Llbgu7YiVZe0Fs',
    appId: '1:692512947576:web:6aa5074ac808e3e64b5c8d',
    messagingSenderId: '692512947576',
    projectId: 'trhal-app',
    authDomain: 'trhal-app.firebaseapp.com',
    storageBucket: 'trhal-app.appspot.com',
    measurementId: 'G-CF7NR1778T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzn7-NFoUn1AARNyslHnXYVRLfPwDUCI',
    appId: '1:692512947576:android:86875e1ae7a7c2e44b5c8d',
    messagingSenderId: '692512947576',
    projectId: 'trhal-app',
    storageBucket: 'trhal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00a3rbYJ1c_NpFj35U3DYWczHzofK8SM',
    appId: '1:692512947576:ios:d478fe01637558d84b5c8d',
    messagingSenderId: '692512947576',
    projectId: 'trhal-app',
    storageBucket: 'trhal-app.appspot.com',
    iosBundleId: 'com.example.terhal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00a3rbYJ1c_NpFj35U3DYWczHzofK8SM',
    appId: '1:692512947576:ios:1b51749fceb40dce4b5c8d',
    messagingSenderId: '692512947576',
    projectId: 'trhal-app',
    storageBucket: 'trhal-app.appspot.com',
    iosBundleId: 'com.example.terhal.RunnerTests',
  );
}
